# BGE-M3 configuration (c16000, o3200)
name: "bge_m3_rag_c16000_o3200"
description: "RAG implementation with BGE-M3 multilingual embeddings (chunk_size=16000, chunk_overlap=3200)"

# Retriever configuration
retriever:
  type: "embedding"
  model_name: "bge-m3"  # Must match the name in your API
  # api_url and auth_token will be injected from environment variables by ExperimentManager
  chunk_size: 16000
  chunk_overlap: 3200
  cache_dir: "cache/vector_stores/bge-m3"