# BM25 configuration (c4000, o800) - Large chunks
name: "bm25_rag_c4000_o800"
description: "BM25 retrieval baseline with large chunks (chunk_size=4000, chunk_overlap=800)"

# Retriever configuration
retriever:
  type: "bm25"
  chunk_size: 4000
  chunk_overlap: 800
  min_score_threshold: 0.0
  
  # Standard BM25 parameters
  k1: 1.5
  b: 0.75
  epsilon: 0.25 