# Gemini Embedding configuration (c2000, o400)
name: "gemini_rag_c2000_o400"
description: "RAG implementation with Google's Gemini embedding model (chunk_size=2000, chunk_overlap=400)"

# Retriever configuration
retriever:
  type: "gemini"  # Will use the GeminiRetriever class
  model_name: "text-embedding-004"  # Use text-embedding-004 which is confirmed working
  chunk_size: 2000
  chunk_overlap: 400
  cache_dir: "cache/vector_stores/gemini"

# Use default generation settings from base_config.yaml