# Multi-Hop Retrieval configuration
name: "multihop_rag"
description: "Multi-hop retrieval using query reformulation"

# Retriever configuration
retriever:
  type: "multihop"
  num_queries: 3  # Number of additional queries to generate
  llm_model: "gemini-2.0-flash"  # Model for query generation
  temperature: 0.5
  combination_strategy: "reciprocal_rank_fusion"  # "union" or "reciprocal_rank_fusion"
  
  # Base retriever configuration - using Gemini embeddings
  base_retriever:
    type: "gemini"
    model_name: "text-embedding-004"
    chunk_size: 1000
    chunk_overlap: 200
    cache_dir: "cache/vector_stores/multihop_gemini"

# Generation configuration
generation:
  model: "gemini-2.0-flash"
  temperature: 0.7