# Nomic embeddings configuration (c500, o100)
name: "nomic_rag_c500_o100"
description: "RAG implementation with Nomic multilingual embeddings (chunk_size=500, chunk_overlap=100)"

# Retriever configuration
retriever:
  type: "embedding"
  model_name: "nomic"  # Must match the name in your API
  # api_url and auth_token will be injected from environment variables by ExperimentManager
  chunk_size: 500
  chunk_overlap: 100
  cache_dir: "cache/vector_stores/nomic"
  is_query: false  # Default to document mode for indexing