# Nomic configuration (c300, o60) - Lower bound test
name: "nomic_rag_c300_o60"
description: "RAG implementation with Nomic multilingual embeddings (chunk_size=300, chunk_overlap=60)"

# Retriever configuration
retriever:
  type: "embedding"
  model_name: "nomic"
  chunk_size: 300
  chunk_overlap: 60
  cache_dir: "cache/vector_stores/nomic" 