# Standard RAG configuration (c500, o100)
name: "standard_rag_c500_o100"
description: "Standard RAG implementation with E5 embeddings (chunk_size=500, chunk_overlap=100)"

# Retriever configuration
retriever:
  type: "embedding"
  model_name: "e5"
  # api_url and auth_token will be injected from environment variables by ExperimentManager
  chunk_size: 500
  chunk_overlap: 100
  cache_dir: "cache/vector_stores"

# Use default generation settings from base_config.yaml