# Standard RAG configuration (c1000, o200)
name: "standard_rag_c1000_o200"
description: "Standard RAG implementation with E5 embeddings (chunk_size=1000, chunk_overlap=200)"

# Retriever configuration
retriever:
  type: "embedding"
  model_name: "e5"
  # api_url and auth_token will be injected from environment variables by ExperimentManager
  chunk_size: 1000
  chunk_overlap: 200
  cache_dir: "cache/vector_stores"

# Use default generation settings from base_config.yaml
