# Standard RAG configuration (c300, o60) - Lower bound test
name: "standard_rag_c300_o60"
description: "Standard RAG implementation with E5 embeddings (chunk_size=300, chunk_overlap=60)"

# Retriever configuration
retriever:
  type: "embedding"
  model_name: "e5"
  chunk_size: 300
  chunk_overlap: 60
  cache_dir: "cache/vector_stores" 